android:
  platformName: 'Android'
  deviceName: 'emulator-5554'
  platformVersion: '10.0'
  orientation: 'PORTRAIT'
  installerFile: './apps/Android.apk.zip'

ios:
  platformName: 'iOS'
  deviceName: 'iPhone 12 Pro Max'
  platformVersion: '14.4'
  orientation: 'PORTRAIT'
  installerFile: './apps/CalendarApp.zip'